/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as ApiDeskSessionRouteImport } from './routes/api.desk-session'
import { Route as TickerSymbolRouteImport } from './routes/ticker.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskSessionRoute = ApiDeskSessionRouteImport.update({
  id: '/api/desk-session',
  path: '/api/desk-session',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerSymbolRoute = TickerSymbolRouteImport.update({
  id: '/ticker/$symbol',
  path: '/ticker/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/desk': typeof DeskRoute
  '/news': typeof NewsRoute
  '/options': typeof OptionsRoute
  '/api/desk-session': typeof ApiDeskSessionRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/desk': typeof DeskRoute
  '/news': typeof NewsRoute
  '/options': typeof OptionsRoute
  '/api/desk-session': typeof ApiDeskSessionRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/desk': typeof DeskRoute
  '/news': typeof NewsRoute
  '/options': typeof OptionsRoute
  '/api/desk-session': typeof ApiDeskSessionRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/desk'
    | '/news'
    | '/options'
    | '/api/desk-session'
    | '/ticker/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/desk'
    | '/news'
    | '/options'
    | '/api/desk-session'
    | '/ticker/$symbol'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/desk'
    | '/news'
    | '/options'
    | '/api/desk-session'
    | '/ticker/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  DeskRoute: typeof DeskRoute
  NewsRoute: typeof NewsRoute
  OptionsRoute: typeof OptionsRoute
  ApiDeskSessionRoute: typeof ApiDeskSessionRoute
  TickerSymbolRoute: typeof TickerSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-session': {
      id: '/api/desk-session'
      path: '/api/desk-session'
      fullPath: '/api/desk-session'
      preLoaderRoute: typeof ApiDeskSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker/$symbol': {
      id: '/ticker/$symbol'
      path: '/ticker/$symbol'
      fullPath: '/ticker/$symbol'
      preLoaderRoute: typeof TickerSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  DeskRoute: DeskRoute,
  NewsRoute: NewsRoute,
  OptionsRoute: OptionsRoute,
  ApiDeskSessionRoute: ApiDeskSessionRoute,
  TickerSymbolRoute: TickerSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
